language: node_js
sudo: required
dist: trusty
node_js:
  - "8"
before_script:
  - npm install
script:
  - npm test
env:
  # evade checks in config.js
  - CLIENT_ID=placeholder CLIENT_SECRET=placeholder GCLOUD_PROJECT=placeholder CLOUD_BUCKET=placeholder FIREBASE_AUTH=placeholder API_TOKENS="abcdefghijk"
  