language: node_js
sudo: required
dist: trusty
node_js:
  - "6"
before_script:
  - npm install
script:
  - npm test
env:
  # evade checks in config.js
  - CLIENT_ID=dummy CLIENT_SECRET=dummy GCLOUD_PROJECT=dummy CLOUD_BUCKET=dummy